#!/bin/bash

NAME=fastapi-app
DIR=/root/podsearch/app
WORKERS=3
WORKER_CLASS=uvicorn.workers.UvicornWorker
BIND="0.0.0.0:8000"
LOG_LEVEL=error

cd $DIR
poetry install
export OPENAI_API_KEY="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"

exec poetry run gunicorn server:app \
  --name $NAME \
  --workers $WORKERS \
  --worker-class $WORKER_CLASS \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-
